language: node_js

sudo: false

node_js:
  - 'stable'
  - '12'

install: yarn install
cache:
  yarn: true

script: echo "Running tests against $(node -v)..."

jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage --forceExit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

before_install:
  - mysql -e 'CREATE DATABASE casbin;'

services:
  - mysql
