name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: 'root'
      - run: mysql -e 'CREATE DATABASE casbin;'
      - run: yarn
